/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosonyexperia;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus13santi
 */
public class Interfaz extends javax.swing.JFrame {
    
    final JFrame frame = new JFrame();
    File file;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CamarasProducidas = new javax.swing.JTextField();
        DiasTranscurridos = new javax.swing.JTextField();
        pantallasProducidas = new javax.swing.JTextField();
        PinCargaProducidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonesProducidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JefeEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        GerenteEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DiasRestantes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TelefonosProducidos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        EncontroJefe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gastosSalarios = new javax.swing.JTextField();
        numProductoresBotones = new javax.swing.JTextField();
        numProductoresPantallas = new javax.swing.JTextField();
        numProductoresPinCarga = new javax.swing.JTextField();
        numEnsambladores = new javax.swing.JTextField();
        numTelefonosVendidos = new javax.swing.JTextField();
        SalarioJefe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        numProductoresCamaras = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BtnDelProBotones = new javax.swing.JButton();
        btnAggProBotones = new javax.swing.JButton();
        BtnAggProPantallas = new javax.swing.JButton();
        BtnAggProPcarga = new javax.swing.JButton();
        btnAggEnsamblador = new javax.swing.JButton();
        btnDelEnsamblador = new javax.swing.JButton();
        BtnDelProPcarga = new javax.swing.JButton();
        BtnDelProPantallas = new javax.swing.JButton();
        BtnAggProCamaras = new javax.swing.JButton();
        BtnDelProCamaras = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Oficina");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 60, 30));

        CamarasProducidas.setEditable(false);
        CamarasProducidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamarasProducidasActionPerformed(evt);
            }
        });
        jPanel1.add(CamarasProducidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 40, -1));

        DiasTranscurridos.setEditable(false);
        DiasTranscurridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasTranscurridosActionPerformed(evt);
            }
        });
        jPanel1.add(DiasTranscurridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 40, -1));

        pantallasProducidas.setEditable(false);
        pantallasProducidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallasProducidasActionPerformed(evt);
            }
        });
        jPanel1.add(pantallasProducidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, -1));

        PinCargaProducidos.setEditable(false);
        PinCargaProducidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinCargaProducidosActionPerformed(evt);
            }
        });
        jPanel1.add(PinCargaProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 40, -1));

        jLabel2.setText("Dias transcurridos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel3.setText("Camaras");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel4.setText("Telefonos Producidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        jLabel5.setText("Pantallas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        botonesProducidos.setEditable(false);
        botonesProducidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonesProducidosActionPerformed(evt);
            }
        });
        jPanel1.add(botonesProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 40, -1));

        jLabel6.setText("Botones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JefeEstado.setEditable(false);
        JefeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JefeEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(JefeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 80, -1));

        jLabel7.setText("Jefe Jugando");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        GerenteEstado.setEditable(false);
        GerenteEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenteEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(GerenteEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 80, -1));

        jLabel8.setText("Telefonos Vendidos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        DiasRestantes.setEditable(false);
        DiasRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasRestantesActionPerformed(evt);
            }
        });
        jPanel1.add(DiasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 40, -1));

        jLabel9.setText("Gastos Salarios");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        TelefonosProducidos.setEditable(false);
        TelefonosProducidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosProducidosActionPerformed(evt);
            }
        });
        jPanel1.add(TelefonosProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 40, -1));

        jLabel10.setText("Pines de Carga");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        btnComenzar.setBackground(new java.awt.Color(102, 153, 255));
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setText("COMENZAR");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, 50));

        EncontroJefe.setEditable(false);
        EncontroJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncontroJefeActionPerformed(evt);
            }
        });
        jPanel1.add(EncontroJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 40, -1));

        jLabel11.setText("Camaras");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        gastosSalarios.setEditable(false);
        gastosSalarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosSalariosActionPerformed(evt);
            }
        });
        jPanel1.add(gastosSalarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 60, -1));

        numProductoresBotones.setEditable(false);
        numProductoresBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProductoresBotonesActionPerformed(evt);
            }
        });
        jPanel1.add(numProductoresBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));

        numProductoresPantallas.setEditable(false);
        numProductoresPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProductoresPantallasActionPerformed(evt);
            }
        });
        jPanel1.add(numProductoresPantallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 40, -1));

        numProductoresPinCarga.setEditable(false);
        numProductoresPinCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProductoresPinCargaActionPerformed(evt);
            }
        });
        jPanel1.add(numProductoresPinCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 40, -1));

        numEnsambladores.setEditable(false);
        numEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numEnsambladoresActionPerformed(evt);
            }
        });
        jPanel1.add(numEnsambladores, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 40, -1));

        numTelefonosVendidos.setEditable(false);
        numTelefonosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTelefonosVendidosActionPerformed(evt);
            }
        });
        jPanel1.add(numTelefonosVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 50, -1));

        SalarioJefe.setEditable(false);
        SalarioJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioJefeActionPerformed(evt);
            }
        });
        jPanel1.add(SalarioJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 50, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("SONY EXPERIA VENEZUELA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, 30));

        jLabel13.setText("Salario Jefe $");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel14.setText("Botones");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel15.setText("Pantallas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel16.setText("Pin de Carga");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Ensambladores");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 110, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Almacen");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, 30));

        jLabel19.setText("Jefe");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Productores");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 30));

        numProductoresCamaras.setEditable(false);
        numProductoresCamaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProductoresCamarasActionPerformed(evt);
            }
        });
        jPanel1.add(numProductoresCamaras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 40, -1));

        jLabel21.setText("Dias restantes");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel22.setText("Gerente");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        BtnDelProBotones.setText("-");
        BtnDelProBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelProBotonesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDelProBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 30));

        btnAggProBotones.setText("+");
        btnAggProBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggProBotonesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggProBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 30));

        BtnAggProPantallas.setText("+");
        BtnAggProPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAggProPantallasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAggProPantallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, 30));

        BtnAggProPcarga.setText("+");
        BtnAggProPcarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAggProPcargaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAggProPcarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 50, 30));

        btnAggEnsamblador.setText("+");
        btnAggEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 50, 30));

        btnDelEnsamblador.setText("-");
        btnDelEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 50, 30));

        BtnDelProPcarga.setText("-");
        BtnDelProPcarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelProPcargaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDelProPcarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 50, 30));

        BtnDelProPantallas.setText("-");
        BtnDelProPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelProPantallasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDelProPantallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, 30));

        BtnAggProCamaras.setText("+");
        BtnAggProCamaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAggProCamarasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAggProCamaras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 50, 30));

        BtnDelProCamaras.setText("-");
        BtnDelProCamaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelProCamarasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDelProCamaras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 50, 30));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Ver Estadisticas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 140, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 150));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 10, 160));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 10, 170));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 10, 140));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 10, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CamarasProducidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamarasProducidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamarasProducidasActionPerformed

    private void DiasTranscurridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasTranscurridosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasTranscurridosActionPerformed

    private void pantallasProducidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallasProducidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallasProducidasActionPerformed

    private void PinCargaProducidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinCargaProducidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinCargaProducidosActionPerformed

    private void botonesProducidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonesProducidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonesProducidosActionPerformed

    private void JefeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JefeEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JefeEstadoActionPerformed

    private void GerenteEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenteEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GerenteEstadoActionPerformed

    private void DiasRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasRestantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasRestantesActionPerformed

    private void TelefonosProducidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosProducidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonosProducidosActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        
        if(btnComenzar.getText().equals("COMENZAR") ){
            final JFileChooser fc = new JFileChooser(); 
            int returnVal = fc.showOpenDialog(frame);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                
                if(ProyectoSonyExperia.readCSV(file)){
                    System.out.println(ProyectoSonyExperia.readCSV(file));
                    System.out.println("SE CARGO BIEN EL ARCHIVO");
//                    this.disableBtn(true);
                    ProyectoSonyExperia.exit = false;
                    ProyectoSonyExperia.ensamblar2();
                    btnComenzar.setText("DEJAR DE PRODUCIR");
                } else{
                    System.out.println(ProyectoSonyExperia.readCSV(file));
                    System.out.println("ERROR EN EL ARCHIVO");
                    JOptionPane.showMessageDialog(null, "Error en la lectura del archivo, verifique que:\n- Hay valores correctos en el mismo (numéricos).\n- Los productores iniciales no superan los máximos permitidos.\n- Los datos del archivo son mayores que cero.\n- Existe capacidad en el almacen para poder armar Escritorios.\n- Seleccionó un archivo válido.", "Error al cargar el archivo", JOptionPane.ERROR_MESSAGE);
//                    this.disableBtn(false);
                    ProyectoSonyExperia.exit = true;
                    btnComenzar.setText("COMENZAR");
                    
                }
            } else {
                System.out.println("Open command cancelled by user.");
            }
            System.out.println(returnVal);
            
        }else{
//            this.disableBtn(false);
            
            btnComenzar.setText("COMENZAR A PRODUCIR");
            ProyectoSonyExperia.exit = true;
        }
        
        
//        ProyectoSonyExperia.exit = false;
//        ProyectoSonyExperia.ensamblar2();
//        System.out.println(ProyectoSonyExperia.exit);
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void EncontroJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncontroJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncontroJefeActionPerformed

    private void gastosSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosSalariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastosSalariosActionPerformed

    private void numProductoresBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProductoresBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProductoresBotonesActionPerformed

    private void numProductoresPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProductoresPantallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProductoresPantallasActionPerformed

    private void numProductoresPinCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProductoresPinCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProductoresPinCargaActionPerformed

    private void numEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numEnsambladoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numEnsambladoresActionPerformed

    private void numTelefonosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTelefonosVendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTelefonosVendidosActionPerformed

    private void SalarioJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioJefeActionPerformed

    private void numProductoresCamarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProductoresCamarasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProductoresCamarasActionPerformed

    private void BtnDelProBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelProBotonesActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_botones > 1 ){
            ProyectoSonyExperia.numProd_botones--;
            ProyectoSonyExperia.prod_botones[ProyectoSonyExperia.numProd_botones].despedir();
            numProductoresBotones.setText(""+ProyectoSonyExperia.numProd_botones);
        }else{
            JOptionPane.showMessageDialog(null, "No puedes despedir al ultimo productor de esta clase, el Jefe puede ser despedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BtnDelProBotonesActionPerformed

    private void btnAggProBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggProBotonesActionPerformed
        // TODO add your handling code here:
        
        if( ProyectoSonyExperia.numProd_botones + ProyectoSonyExperia.numProd_camaras + ProyectoSonyExperia.numProd_pinCarga + ProyectoSonyExperia.numProd_pantallas + ProyectoSonyExperia.num_ensambladores < ProyectoSonyExperia.max_trabajadores ){
            ProyectoSonyExperia.prod_botones[ProyectoSonyExperia.numProd_botones] = new ProductorBotones(ProyectoSonyExperia.semBotones, 10,ProyectoSonyExperia.mutexPantalla, ProyectoSonyExperia.dia );
            ProyectoSonyExperia.prod_botones[ProyectoSonyExperia.numProd_botones].start();
            ProyectoSonyExperia.numProd_botones++;
            numProductoresBotones.setText(""+ProyectoSonyExperia.numProd_botones);
        }else{
            JOptionPane.showMessageDialog(null, "La distribucion maxima de trabajadores es de 10. \n Por favor disminuya la cantidad en otra produccion y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAggProBotonesActionPerformed

    private void BtnAggProPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAggProPantallasActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_botones + ProyectoSonyExperia.numProd_camaras + ProyectoSonyExperia.numProd_pinCarga + ProyectoSonyExperia.numProd_pantallas + ProyectoSonyExperia.num_ensambladores < ProyectoSonyExperia.max_trabajadores ){
            ProyectoSonyExperia.prod_pantalla[ProyectoSonyExperia.numProd_pantallas] = new ProductorPantalla(ProyectoSonyExperia.semPantallas, 10,ProyectoSonyExperia.mutexPantalla, ProyectoSonyExperia.dia );
            ProyectoSonyExperia.prod_pantalla[ProyectoSonyExperia.numProd_pantallas].start();
            ProyectoSonyExperia.numProd_pantallas++;
            numProductoresPantallas.setText(""+ProyectoSonyExperia.numProd_pantallas);
        }else{
            JOptionPane.showMessageDialog(null, "La distribucion maxima de trabajadores es de 10. \n Por favor disminuya la cantidad en otra produccion y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnAggProPantallasActionPerformed

    private void BtnAggProPcargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAggProPcargaActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_botones + ProyectoSonyExperia.numProd_camaras + ProyectoSonyExperia.numProd_pinCarga + ProyectoSonyExperia.numProd_pantallas + ProyectoSonyExperia.num_ensambladores < ProyectoSonyExperia.max_trabajadores ){
            ProyectoSonyExperia.prod_pinCarga[ProyectoSonyExperia.numProd_pinCarga] = new ProductorPinCarga(ProyectoSonyExperia.semPinCarga, 10,ProyectoSonyExperia.mutexPantalla, ProyectoSonyExperia.dia );
            ProyectoSonyExperia.prod_pinCarga[ProyectoSonyExperia.numProd_pinCarga].start();
            ProyectoSonyExperia.numProd_pinCarga++;
            numProductoresPinCarga.setText(""+ProyectoSonyExperia.numProd_pinCarga);
        }else{
            JOptionPane.showMessageDialog(null, "La distribucion maxima de trabajadores es de 10. \n Por favor disminuya la cantidad en otra produccion y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnAggProPcargaActionPerformed

    private void btnAggEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggEnsambladorActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_botones + ProyectoSonyExperia.numProd_camaras + ProyectoSonyExperia.numProd_pinCarga + ProyectoSonyExperia.numProd_pantallas + ProyectoSonyExperia.num_ensambladores < ProyectoSonyExperia.max_trabajadores ){
            ProyectoSonyExperia.ensambladores[ProyectoSonyExperia.num_ensambladores] = new Ensamblador(ProyectoSonyExperia.semPinCarga, ProyectoSonyExperia.semPantallas, ProyectoSonyExperia.semCamaras, ProyectoSonyExperia.semBotones, ProyectoSonyExperia.semSonyExperia,  10, ProyectoSonyExperia.mutexPantalla, ProyectoSonyExperia.dia);
            ProyectoSonyExperia.ensambladores[ProyectoSonyExperia.num_ensambladores].start();
            ProyectoSonyExperia.num_ensambladores++;
            numEnsambladores.setText(""+ProyectoSonyExperia.num_ensambladores);
        }else{
            JOptionPane.showMessageDialog(null, "La distribucion maxima de trabajadores es de 10. \n Por favor disminuya la cantidad en otra produccion y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAggEnsambladorActionPerformed

    private void btnDelEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelEnsambladorActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.num_ensambladores > 1 ){
            System.out.println(ProyectoSonyExperia.num_ensambladores);
            ProyectoSonyExperia.num_ensambladores--;
            ProyectoSonyExperia.ensambladores[ProyectoSonyExperia.num_ensambladores].despedir();
            numEnsambladores.setText(""+ProyectoSonyExperia.num_ensambladores);
        }else{
            JOptionPane.showMessageDialog(null, "No puedes despedir al ultimo productor de esta clase, el Jefe puede ser despedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelEnsambladorActionPerformed

    private void BtnDelProPcargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelProPcargaActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_pinCarga > 1 ){
            ProyectoSonyExperia.numProd_pinCarga--;
            ProyectoSonyExperia.prod_pinCarga[ProyectoSonyExperia.numProd_pinCarga].despedir();
            numProductoresPinCarga.setText(""+ProyectoSonyExperia.numProd_pinCarga);
        }else{
            JOptionPane.showMessageDialog(null, "No puedes despedir al ultimo productor de esta clase, el Jefe puede ser despedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDelProPcargaActionPerformed

    private void BtnDelProPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelProPantallasActionPerformed
        // TODO add your handling code here:
        if( ProyectoSonyExperia.numProd_pantallas > 1 ){
            ProyectoSonyExperia.numProd_pantallas--;
            ProyectoSonyExperia.prod_pantalla[ProyectoSonyExperia.numProd_pantallas].despedir();
            numProductoresPantallas.setText(""+ProyectoSonyExperia.numProd_pantallas);
        }else{
            JOptionPane.showMessageDialog(null, "No puedes despedir al ultimo productor de esta clase, el Jefe puede ser despedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDelProPantallasActionPerformed

    private void BtnAggProCamarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAggProCamarasActionPerformed
        // TODO add your handling code here:
       if( ProyectoSonyExperia.numProd_botones + ProyectoSonyExperia.numProd_camaras + ProyectoSonyExperia.numProd_pinCarga + ProyectoSonyExperia.numProd_pantallas + ProyectoSonyExperia.num_ensambladores < ProyectoSonyExperia.max_trabajadores ){
            ProyectoSonyExperia.prod_camara[ProyectoSonyExperia.numProd_camaras] = new ProductorCamara(ProyectoSonyExperia.semCamaras, 10,ProyectoSonyExperia.mutexPantalla, ProyectoSonyExperia.dia );
            ProyectoSonyExperia.prod_camara[ProyectoSonyExperia.numProd_camaras].start();
            ProyectoSonyExperia.numProd_camaras++;
            numProductoresCamaras.setText(""+ProyectoSonyExperia.numProd_camaras);
        }else{
            JOptionPane.showMessageDialog(null, "La distribucion maxima de trabajadores es de 10. \n Por favor disminuya la cantidad en otra produccion y vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BtnAggProCamarasActionPerformed

    private void BtnDelProCamarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelProCamarasActionPerformed
        // TODO add your handling code here:
        
        if( ProyectoSonyExperia.numProd_camaras > 1 ){
            ProyectoSonyExperia.numProd_camaras--;
            ProyectoSonyExperia.prod_camara[ProyectoSonyExperia.numProd_camaras].despedir();
            numProductoresCamaras.setText(""+ProyectoSonyExperia.numProd_camaras);
        }else{
            JOptionPane.showMessageDialog(null, "No puedes despedir al ultimo productor de esta clase, el Jefe puede ser despedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnDelProCamarasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAggProCamaras;
    private javax.swing.JButton BtnAggProPantallas;
    private javax.swing.JButton BtnAggProPcarga;
    private javax.swing.JButton BtnDelProBotones;
    private javax.swing.JButton BtnDelProCamaras;
    private javax.swing.JButton BtnDelProPantallas;
    private javax.swing.JButton BtnDelProPcarga;
    public static volatile javax.swing.JTextField CamarasProducidas;
    public static volatile javax.swing.JTextField DiasRestantes;
    public static volatile javax.swing.JTextField DiasTranscurridos;
    public static volatile javax.swing.JTextField EncontroJefe;
    public static volatile javax.swing.JTextField GerenteEstado;
    public static volatile javax.swing.JTextField JefeEstado;
    public static volatile javax.swing.JTextField PinCargaProducidos;
    public static volatile javax.swing.JTextField SalarioJefe;
    public static volatile javax.swing.JTextField TelefonosProducidos;
    public static volatile javax.swing.JTextField botonesProducidos;
    private javax.swing.JButton btnAggEnsamblador;
    private javax.swing.JButton btnAggProBotones;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnDelEnsamblador;
    public static volatile javax.swing.JTextField gastosSalarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public static volatile javax.swing.JTextField numEnsambladores;
    public static volatile javax.swing.JTextField numProductoresBotones;
    public static volatile javax.swing.JTextField numProductoresCamaras;
    public static volatile javax.swing.JTextField numProductoresPantallas;
    public static volatile javax.swing.JTextField numProductoresPinCarga;
    public static volatile javax.swing.JTextField numTelefonosVendidos;
    public static volatile javax.swing.JTextField pantallasProducidas;
    // End of variables declaration//GEN-END:variables
}
